//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_1_Football_MVC.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BussInfo
    {
        public string BussID { get; set; }
        public string BoardingPoint { get; set; }
        public string TravelDate { get; set; }
        public string Amount { get; set; }
        public string Rating { get; set; }
    }
}
