//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_1_Football_MVC.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderItem1 { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
    
        public virtual Order1 Order1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
